<?php
$items = [
    new Cibo("Crocchete per cani", 15.49, "https://www.ideashoppingcenter.it/files/archivio_Files/Foto/44645_2.JPG", new Categoria("Cani"), "1 kg", "Alimenti secchi per cani", "1 kg di crocchette bilanciate per cani Wolf of Wilderness, senza cereali né glutine, ispirate all'alimentazione originaria del lupo in natura"),
    new Gioco("Gioco per gatti  corda con due palline", 8.19, "https://ss-pics.s3.eu-west-1.amazonaws.com/files/2056905/page-set-di-palline-con-coda-e-sonaglio-in-plastica.jpg?1636994304", new Categoria("gatti"), "Plastica", "Da mordere", "Gioco dai colori festosi per gatti, unisce una corda colorata in poliestere a 2 palline in TPR con punte"),
    new Cuccia("Letto Trixie Elika", 28.99, "https://shop-cdn-m.mediazs.com/bilder/letto/batumi/3/400/1_203335_geop_zooplusexclusive_katzenbett_batumi_hs_04_3.jpg", new Categoria("gatti"), "1/2 kg", "50cm circonferenza", "Letto per gatti, cuccioli e cani di piccola taglia, in morbido peluche, confortevole bordo alto di facile accesso"),
    new Cibo("Crocchete per cani", 15.49, "https://www.ideashoppingcenter.it/files/archivio_Files/Foto/44645_2.JPG", new Categoria("Cani"), "1 kg", "Alimenti secchi per cani", "1 kg di crocchette bilanciate per cani Wolf of Wilderness, senza cereali né glutine, ispirate all'alimentazione originaria del lupo in natura"),
    new Gioco("Gioco per gatti  corda con due palline", 8.19, "https://ss-pics.s3.eu-west-1.amazonaws.com/files/2056905/page-set-di-palline-con-coda-e-sonaglio-in-plastica.jpg?1636994304", new Categoria("gatti"), "Plastica", "Da mordere", "Gioco dai colori festosi per gatti, unisce una corda colorata in poliestere a 2 palline in TPR con punte"),
    new Cuccia("Letto Trixie Elika", 28.99, "https://shop-cdn-m.mediazs.com/bilder/letto/batumi/3/400/1_203335_geop_zooplusexclusive_katzenbett_batumi_hs_04_3.jpg", new Categoria("gatti"), "1/2 kg", "50cm circonferenza", "Letto per gatti, cuccioli e cani di piccola taglia, in morbido peluche, confortevole bordo alto di facile accesso"),
    new Cuccia("Letto Trixie Elika", 28.99, "https://shop-cdn-m.mediazs.com/bilder/letto/batumi/3/400/1_203335_geop_zooplusexclusive_katzenbett_batumi_hs_04_3.jpg", new Categoria("gatti"), "1/2 kg", "50cm circonferenza", "Letto per gatti, cuccioli e cani di piccola taglia, in morbido peluche, confortevole bordo alto di facile accesso"),
    new Cibo("Crocchete per cani", 15.49, "https://www.ideashoppingcenter.it/files/archivio_Files/Foto/44645_2.JPG", new Categoria("Cani"), "1 kg", "Alimenti secchi per cani", "1 kg di crocchette bilanciate per cani Wolf of Wilderness, senza cereali né glutine, ispirate all'alimentazione originaria del lupo in natura"),
    new Gioco("Gioco per gatti  corda con due palline", 8.19, "https://ss-pics.s3.eu-west-1.amazonaws.com/files/2056905/page-set-di-palline-con-coda-e-sonaglio-in-plastica.jpg?1636994304", new Categoria("gatti"), "Plastica", "Da mordere", "Gioco dai colori festosi per gatti, unisce una corda colorata in poliestere a 2 palline in TPR con punte"),
    new Cuccia("Letto Trixie Elika", 28.99, "https://shop-cdn-m.mediazs.com/bilder/letto/batumi/3/400/1_203335_geop_zooplusexclusive_katzenbett_batumi_hs_04_3.jpg", new Categoria("gatti"), "1/2 kg", "50cm circonferenza", "Letto per gatti, cuccioli e cani di piccola taglia, in morbido peluche, confortevole bordo alto di facile accesso")
];
